os: Visual Studio 2015

# Version format
version: 0.3.0.{build}

cache:
  - Source\packages -> **\packages.config   # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

branches:
  only:
    - develop
    - master
    
# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=rtm  

build_script:
  - cd Packaging
  - build-appveyor.bat

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip
  

deploy:
 # MyGet Deployment for beta releases  
  - provider: NuGet
    server: https://www.myget.org/F/janvanhelvoort/api/v2/package
    api_key:
      secure: y4EM8fqJBHkcJJBKwrVktFXOez5vDHSwKCR8UuVKL0KQzUSGbwMsfPOwOtzdN9VF
    artifact: /.*\.nupkg/
    on:
      branch: develop
      
 # GitHub Deployment for releases
  - provider: GitHub
    auth_token:
      secure: luRGDANEw9HXHhcwys/ci3jz309ZZ/VJ/L1HzM6sORpfWMscAnrK3YEs6KOXsjJv
    artifact: /.*\.zip/            # upload all Zip packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only

# NuGet Deployment for releases
  - provider: NuGet
    server:
    api_key:
      secure: Sucm5bXRO318pNwIHtgyykGEiq7MG1QvEwbQyWUacSKLFr1PjMw5XDv/1/gHGlGv
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true